server:
  port: 8009
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wisdom?serverTimezone=GMT%2B8
    username: root
    password: 202333
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath:com/rjx/oss/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI4G86y9kLCohNkGSEJHTW
      keysecret: DOVtDVZ80ThVkMtQUlMBFKGcwr6QOI
      bucketname: eduguli1010